name: VyHub
version: '${project.version}'
main: net.vyhub.VyHubMinecraft.VyHub
api-version: 1.18

depend:
  - LuckPerms
commands:
  login:
    description: 'Login user for VyHub'
    aliases: ['l']

  timeban:
    description: 'Ban user for a certain time'
    aliases: ['tb']

  warn:
    description: 'Player Warning'
    aliases: ['w']

