name: Vyhub
version: '${project.version}'
main: com.minecraft.Vyhub
api-version: 1.18


commands:
  login:
    description: 'Login user for VyHub'
    aliases: ['l']

  timeban:
    description: 'Ban user for a certain time'
    aliases: ['tb']


