name: VyHub
version: '${project.version}'
description: 'VyHub plugin to manage and monetize your Minecraft server. Using VyHub you can create an store to sell items.'
main: net.vyhub.VyHubPlugin
api-version: 1.13

depend:
  - LuckPerms
commands:
  login:
    description: 'Login user for VyHub'
    usage: '/login <uuid>'
    aliases: ['l']

  timeban:
    description: 'Ban user for a certain time'
    aliases: ['tb']
    usage: '/timeban <player> <minutes> <reason>'

  warn:
    description: 'Warn a player'
    aliases: ['w']
    usage: '/warn <player> <reason>'

  vh_config:
    description: 'Set VyHub config values'
    usage: '/vh_config <key> <value>'

