name: VyHub
version: '${project.version}'
description: 'VyHub plugin to manage and monetize your Minecraft server. You can create your webstore for free with VyHub!'
main: net.vyhub.VyHubPlugin
api-version: 1.13

softdepend:
  - LuckPerms
commands:
  vylogin:
    description: 'Login user to VyHub'
    usage: '/vylogin <uuid>'

  timeban:
    description: 'Ban user for a certain time'
    aliases: ['tb']
    usage: '/timeban <player> <minutes> <reason>'

  warn:
    description: 'Warn a player'
    aliases: ['w']
    usage: '/warn <player> <reason>'

  vh_config:
    description: 'Set VyHub config values'
    usage: '/vh_config <key> <value>'

  vh_setup:
    description: 'Setup VyHub plugin'
    usage: '/vh_setup <api_key> <api_url> <server_id>'

